import NepaliDate from 'nepali-date-converter';

/**
 * Generates a professional, bank-grade CSV financial statement.
 * Handles column alignment perfectly to avoid data shifting.
 */
export const generateFinancialStatement = ({ transactions, summary, period, type, user }) => {

    // --- 1. Formatting Helpers ---

    // Format Currency (Standard 1,200.00 format without symbol to prevent Excel issues)
    const formatMoney = (amount) => {
        if (typeof amount !== 'number') return "0.00";
        return new Intl.NumberFormat('en-IN', { 
            minimumFractionDigits: 2,
            maximumFractionDigits: 2 
        }).format(amount).replace(/,/g, ''); // Remove commas for raw CSV number compatibility if needed, or keep for visual. 
        // For CSV visual compatibility, we will keep commas but wrap in quotes below.
    };

    const formatMoneyVisual = (amount) => {
        if (typeof amount !== 'number') return "";
        // Returns "1,200.00"
        return new Intl.NumberFormat('en-IN', { 
            minimumFractionDigits: 2,
            maximumFractionDigits: 2 
        }).format(amount);
    };

    // Get Nepali Date (BS)
    const getNepaliDate = (dateString) => {
        try {
            if (!dateString) return "-";
            const date = new Date(dateString);
            return new NepaliDate(date).format('YYYY-MM-DD');
        } catch (e) {
            return "N/A";
        }
    };

    // Get English Date (AD)
    const getEnglishDate = (dateString) => {
        if (!dateString) return "-";
        return new Date(dateString).toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'short', 
            day: 'numeric' 
        });
    };

    // CRITICAL: Sanitize text to prevent CSV column shifting
    // Wraps text in quotes if it contains commas or newlines
    const sanitize = (text) => {
        if (!text) return "";
        const stringText = String(text);
        // Replace double quotes with two double quotes (CSV standard escaping)
        const escaped = stringText.replace(/"/g, '""'); 
        return `"${escaped}"`;
    };

    // --- 2. Header Section (Metadata) ---
    
    const generatedOnBS = getNepaliDate(new Date());
    const generatedOnAD = getEnglishDate(new Date());
    const reportTitle = type === 'yearly' ? 'ANNUAL FISCAL REPORT' : 'MONTHLY FINANCIAL STATEMENT';

    // The header rows array
    const headerRows = [
        ['Geko Works Nepal Pvt Ltd'],
        ['OFFICIAL FINANCIAL STATEMENT'],
        [''], // Empty row
        ['Report Type', sanitize(reportTitle)],
        ['Statement Period', sanitize(period)],
        ['Generated By', sanitize(user?.name || 'System')],
        ['Generated Date', sanitize(`${generatedOnBS} (BS) | ${generatedOnAD} (AD)`)],
        ['Currency', 'NPR'],
        [''],
        ['EXECUTIVE SUMMARY'],
        ['Total Income', sanitize(formatMoneyVisual(summary.totalIncome))],
        ['Total Expenses', sanitize(formatMoneyVisual(summary.totalExpenses))],
        ['Net Position', sanitize(formatMoneyVisual(summary.netProfit))],
        ['Closing Status', summary.netProfit >= 0 ? 'PROFIT' : 'LOSS'],
        [''],
        ['TRANSACTION DETAILS']
    ];

    // --- 3. Table Columns (Exact Match to your Request) ---

    const tableHeaders = [
        'Nepali Date (BS)', 
        'English Date (AD)', 
        'Title', 
        'Description / Notes', 
        'Category', 
        'Type', 
        'Debit (Out)', 
        'Credit (In)'
    ];

    // --- 4. Map Data to Rows (Fixing the "Same Box" issue) ---

    const dataRows = transactions.map(t => {
        // Logic: Income/Deposit/Sales goes to Credit Column. Expense/Withdrawal goes to Debit Column.
        // We use loose matching to catch "Deposit", "Income", "Sales" etc.
        const typeStr = t.type || "";
        const isCredit = typeStr.includes('Income') || typeStr.includes('Deposit') || typeStr.includes('Sales');
        
        // We put the formatted money string in quotes so the comma in "1,000" doesn't split columns
        const debitValue = !isCredit ? sanitize(formatMoneyVisual(t.amount)) : "";
        const creditValue = isCredit ? sanitize(formatMoneyVisual(t.amount)) : "";

        return [
            sanitize(getNepaliDate(t.date)),              // 1. BS Date
            sanitize(getEnglishDate(t.date)),             // 2. AD Date
            sanitize(t.title || "Untitled"),              // 3. Title
            sanitize(t.description || "-"),               // 4. Description
            sanitize(t.category || "General"),            // 5. Category
            sanitize(t.type?.toUpperCase() || "UNKNOWN"), // 6. Type
            debitValue,                                   // 7. Debit (Out)
            creditValue                                   // 8. Credit (In)
        ];
    });

    // --- 5. Construct CSV & Download ---

    // Combine Header + Columns + Data
    const csvArray = [...headerRows, tableHeaders, ...dataRows];
    
    // Join array into CSV string
    const csvContent = csvArray.map(e => e.join(",")).join("\n");

    // Create Blob
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    
    // Generate Filename
    const safePeriod = period ? period.replace(/ /g, '_').replace(/,/g, '') : 'Statement';
    const fileName = `Statement_${safePeriod}_${generatedOnBS}.csv`;

    // Trigger Download
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', fileName);
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
};